In [1]:
import pandas as pd
import math
import numpy as np
import collections

In [2]:
medication=pd.read_csv("medication.csv")

In [3]:
vitalp=pd.read_csv("vitalPeriodic.csv")

In [4]:
nurseChart=pd.read_csv("nurseCharting.csv")

In [5]:
gcs=[]
d_gcs=[]
for row in nurseChart.itertuples():
    if((row.nursingchartcelltypecat=="Scores" and row.nursingchartcelltypevallabel=="Glasgow coma score")):
        #gcs.append([row.patientunitstayid,row.nursingchartentryoffset,row.nursingchartcelltypevallabel,int(row.nursingchartvalue)])
        d_gcs.append(row)    
d_gcs=pd.DataFrame(d_gcs)

In [6]:
d_gcs.nursingchartvalue=pd.to_numeric(d_gcs.nursingchartvalue,errors='coerce')
d_gcs=d_gcs.dropna(subset=['nursingchartvalue'])
d_gcs.nursingchartvalue=d_gcs.nursingchartvalue.astype(int)

In [7]:
d_gcs=d_gcs.drop(['Index'],axis=1)

In [8]:
d_gcs.head()

,nursingchartid,patientunitstayid,nursingchartoffset,nursingchartentryoffset,nursingchartcelltypecat,nursingchartcelltypevallabel,nursingchartcelltypevalname,nursingchartvalue
0,174878135,142493,102,102,Scores,Glasgow coma score,GCS Total,10
1,174894838,142493,582,582,Scores,Glasgow coma score,GCS Total,15
2,265154559,142493,12,12,Scores,Glasgow coma score,GCS Total,11
3,211010241,142493,342,342,Scores,Glasgow coma score,GCS Total,15
4,229054198,142494,293,293,Scores,Glasgow coma score,GCS Total,15

In [9]:
d_gcs.sort_values(by=['patientunitstayid','nursingchartentryoffset'],inplace=True)

In [10]:
infusiondrug=pd.read_csv("infusionDrug.csv")

In [11]:
lab=pd.read_csv("lab.csv")

In [12]:
lab_processed=[]
SOFA_req=['paO2','platelets x 1000','total bilirubin','urinary creatinine']
for row in lab.itertuples():
    if(row.labname in SOFA_req):
        lab_processed.append(row)

In [13]:
lab_processed=pd.DataFrame(lab_processed)
lab_processed=lab_processed.drop(['Index'],axis=1)

In [14]:
lab_processed.sort_values(by=['patientunitstayid','labresultoffset'],inplace=True)

In [15]:
lab_processed.head()

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
2,54100434,142493,50,3,platelets x 1000,65.0,65,K/mcL,K/mcL,70
0,67615679,142493,180,7,paO2,197.0,197,mm Hg,mm Hg,188
1,66865075,142493,237,7,paO2,156.0,156,mm Hg,mm Hg,249
3,54833226,142493,292,3,platelets x 1000,120.0,120,K/mcL,K/mcL,299
4,53675887,142493,667,3,platelets x 1000,126.0,126,K/mcL,K/mcL,683

In [16]:
test=pd.merge(d_gcs,lab_processed,how="outer",on=['patientunitstayid'])

In [17]:
test=test.drop(['nursingchartoffset','nursingchartcelltypecat','nursingchartid','labid','labresulttext'],axis=1)

In [18]:
testg=test.groupby(['patientunitstayid','labresultoffset'])

In [19]:
testg.first()

                                   nursingchartentryoffset  \
patientunitstayid labresultoffset
142493             50.0                               12.0
                   180.0                              12.0
                   237.0                              12.0
                   292.0                              12.0
                   667.0                              12.0
142494             1033.0                           -187.0
142495            -238.0                            -244.0
                  -63.0                             -244.0
                   806.0                            -244.0
                   2286.0                           -244.0
                   2821.0                           -244.0
                   2897.0                           -244.0
                   2940.0                           -244.0
                   2970.0                           -244.0
                   2992.0                           -244.0
                   2994.0                           -244.0
142674            -1986.0                             25.0
                  -604.0                              25.0
                   670.0                              25.0
143599            -284.0                               NaN
                   164.0                               NaN
                   412.0                               NaN
                   1846.0                              NaN
                   3266.0                              NaN
                   4734.0                              NaN
143603             35.0                             1120.0
                   300.0                            1120.0
                   321.0                            1120.0
                   1735.0                           1120.0
                   1755.0                           1120.0
...                                                    ...
1133552            1395.0                           -216.0
                   2821.0                           -216.0
                   2933.0                           -216.0
                   4278.0                           -216.0
                   5007.0                           -216.0
                   5730.0                           -216.0
1135185            1031.0                            375.0
                   2504.0                            375.0
                   4055.0                            375.0
                   5461.0                            375.0
                   6907.0                            375.0
                   8363.0                            375.0
1135186           -439.0                            -450.0
                   62.0                             -450.0
                   413.0                            -450.0
                   844.0                            -450.0
                   938.0                            -450.0
                   1104.0                           -450.0
                   1513.0                           -450.0
                   1873.0                           -450.0
                   2119.0                           -450.0
                   2600.0                           -450.0
                   2679.0                           -450.0
                   2998.0                           -450.0
                   3298.0                           -450.0
                   3583.0                           -450.0
                   4213.0                           -450.0
                   4943.0                           -450.0
                   6414.0                           -450.0
                   7823.0                           -450.0

                                  nursingchartcelltypevallabel  \
patientunitstayid labresultoffset
142493             50.0                     Glasgow coma score
                   180.0                    Glasgow coma score
                   237.0                    Glasgow coma score
                   292.0                    Glasgow coma score
                   667.0                    Glasgow coma score
142494             1033.0                   Glasgow coma score
142495            -238.0                    Glasgow coma score
                  -63.0                     Glasgow coma score
                   806.0                    Glasgow coma score
                   2286.0                   Glasgow coma score
                   2821.0                   Glasgow coma score
                   2897.0                   Glasgow coma score
                   2940.0                   Glasgow coma score
                   2970.0                   Glasgow coma score
                   2992.0                   Glasgow coma score
                   2994.0                   Glasgow coma score
142674            -1986.0                   Glasgow coma score
                  -604.0                    Glasgow coma score
                   670.0                    Glasgow coma score
143599            -284.0                                   NaN
                   164.0                                   NaN
                   412.0                                   NaN
                   1846.0                                  NaN
                   3266.0                                  NaN
                   4734.0                                  NaN
143603             35.0                     Glasgow coma score
                   300.0                    Glasgow coma score
                   321.0                    Glasgow coma score
                   1735.0                   Glasgow coma score
                   1755.0                   Glasgow coma score
...                                                        ...
1133552            1395.0                   Glasgow coma score
                   2821.0                   Glasgow coma score
                   2933.0                   Glasgow coma score
                   4278.0                   Glasgow coma score
                   5007.0                   Glasgow coma score
                   5730.0                   Glasgow coma score
1135185            1031.0                   Glasgow coma score
                   2504.0                   Glasgow coma score
                   4055.0                   Glasgow coma score
                   5461.0                   Glasgow coma score
                   6907.0                   Glasgow coma score
                   8363.0                   Glasgow coma score
1135186           -439.0                    Glasgow coma score
                   62.0                     Glasgow coma score
                   413.0                    Glasgow coma score
                   844.0                    Glasgow coma score
                   938.0                    Glasgow coma score
                   1104.0                   Glasgow coma score
                   1513.0                   Glasgow coma score
                   1873.0                   Glasgow coma score
                   2119.0                   Glasgow coma score
                   2600.0                   Glasgow coma score
                   2679.0                   Glasgow coma score
                   2998.0                   Glasgow coma score
                   3298.0                   Glasgow coma score
                   3583.0                   Glasgow coma score
                   4213.0                   Glasgow coma score
                   4943.0                   Glasgow coma score
                   6414.0                   Glasgow coma score
                   7823.0                   Glasgow coma score

                                  nursingchartcelltypevalname  \
patientunitstayid labresultoffset
142493             50.0                             GCS Total
                   180.0                            GCS Total
                   237.0                            GCS Total
                   292.0                            GCS Total
                   667.0                            GCS Total
142494             1033.0                           GCS Total
142495            -238.0                            GCS Total
                  -63.0                             GCS Total
                   806.0                            GCS Total
                   2286.0                           GCS Total
                   2821.0                           GCS Total
                   2897.0                           GCS Total
                   2940.0                           GCS Total
                   2970.0                           GCS Total
                   2992.0                           GCS Total
                   2994.0                           GCS Total
142674            -1986.0                           GCS Total
                  -604.0                            GCS Total
                   670.0                            GCS Total
143599            -284.0                                  NaN
                   164.0                                  NaN
                   412.0                                  NaN
                   1846.0                                 NaN
                   3266.0                                 NaN
                   4734.0                                 NaN
143603             35.0                             GCS Total
                   300.0                            GCS Total
                   321.0                            GCS Total
                   1735.0                           GCS Total
                   1755.0                           GCS Total
...                                                       ...
1133552            1395.0                           GCS Total
                   2821.0                           GCS Total
                   2933.0                           GCS Total
                   4278.0                           GCS Total
                   5007.0                           GCS Total
                   5730.0                           GCS Total
1135185            1031.0                              Verbal
                   2504.0                              Verbal
                   4055.0                              Verbal
                   5461.0                              Verbal
                   6907.0                              Verbal
                   8363.0                              Verbal
1135186           -439.0                            GCS Total
                   62.0                             GCS Total
                   413.0                            GCS Total
                   844.0                            GCS Total
                   938.0                            GCS Total
                   1104.0                           GCS Total
                   1513.0                           GCS Total
                   1873.0                           GCS Total
                   2119.0                           GCS Total
                   2600.0                           GCS Total
                   2679.0                           GCS Total
                   2998.0                           GCS Total
                   3298.0                           GCS Total
                   3583.0                           GCS Total
                   4213.0                           GCS Total
                   4943.0                           GCS Total
                   6414.0                           GCS Total
                   7823.0                           GCS Total

                                   nursingchartvalue  labtypeid  \
patientunitstayid labresultoffset
142493             50.0                         11.0        3.0
                   180.0                        11.0        7.0
                   237.0                        11.0        7.0
                   292.0                        11.0        3.0
                   667.0                        11.0        3.0
142494             1033.0                       15.0        3.0
142495            -238.0                        15.0        1.0
                  -63.0                         15.0        3.0
                   806.0                        15.0        3.0
                   2286.0                       15.0        3.0
                   2821.0                       15.0        7.0
                   2897.0                       15.0        7.0
                   2940.0                       15.0        7.0
                   2970.0                       15.0        7.0
                   2992.0                       15.0        3.0
                   2994.0                       15.0        7.0
142674            -1986.0                       15.0        3.0
                  -604.0                        15.0        3.0
                   670.0                        15.0        3.0
143599            -284.0                         NaN        3.0
                   164.0                         NaN        7.0
                   412.0                         NaN        3.0
                   1846.0                        NaN        1.0
                   3266.0                        NaN        3.0
                   4734.0                        NaN        3.0
143603             35.0                          6.0        7.0
                   300.0                         6.0        1.0
                   321.0                         6.0        7.0
                   1735.0                        6.0        3.0
                   1755.0                        6.0        7.0
...                                              ...        ...
1133552            1395.0                       15.0        1.0
                   2821.0                       15.0        1.0
                   2933.0                       15.0        7.0
                   4278.0                       15.0        3.0
                   5007.0                       15.0        3.0
                   5730.0                       15.0        1.0
1135185            1031.0                        4.0        3.0
                   2504.0                        4.0        3.0
                   4055.0                        4.0        3.0
                   5461.0                        4.0        3.0
                   6907.0                        4.0        3.0
                   8363.0                        4.0        3.0
1135186           -439.0                        15.0        3.0
                   62.0                         15.0        3.0
                   413.0                        15.0        3.0
                   844.0                        15.0        3.0
                   938.0                        15.0        7.0
                   1104.0                       15.0        3.0
                   1513.0                       15.0        3.0
                   1873.0                       15.0        3.0
                   2119.0                       15.0        3.0
                   2600.0                       15.0        7.0
                   2679.0                       15.0        7.0
                   2998.0                       15.0        7.0
                   3298.0                       15.0        3.0
                   3583.0                       15.0        3.0
                   4213.0                       15.0        3.0
                   4943.0                       15.0        3.0
                   6414.0                       15.0        3.0
                   7823.0                       15.0        3.0

                                            labname  labresult  \
patientunitstayid labresultoffset
142493             50.0            platelets x 1000       65.0
                   180.0                       paO2      197.0
                   237.0                       paO2      156.0
                   292.0           platelets x 1000      120.0
                   667.0           platelets x 1000      126.0
142494             1033.0          platelets x 1000      121.0
142495            -238.0            total bilirubin        0.6
                  -63.0            platelets x 1000      102.0
                   806.0           platelets x 1000       88.0
                   2286.0          platelets x 1000       82.0
                   2821.0                      paO2      101.0
                   2897.0                      paO2      160.0
                   2940.0                      paO2      165.0
                   2970.0                      paO2      149.0
                   2992.0          platelets x 1000       39.0
                   2994.0                      paO2      147.0
142674            -1986.0          platelets x 1000      204.0
                  -604.0           platelets x 1000      188.0
                   670.0           platelets x 1000      187.0
143599            -284.0           platelets x 1000      210.0
                   164.0                       paO2      120.0
                   412.0           platelets x 1000      162.0
                   1846.0           total bilirubin        0.2
                   3266.0          platelets x 1000      177.0
                   4734.0          platelets x 1000      203.0
143603             35.0                        paO2      366.0
                   300.0            total bilirubin        0.5
                   321.0                       paO2      134.0
                   1735.0          platelets x 1000      299.0
                   1755.0                      paO2      125.0
...                                             ...        ...
1133552            1395.0           total bilirubin        0.4
                   2821.0           total bilirubin        1.2
                   2933.0                      paO2       61.7
                   4278.0          platelets x 1000      210.0
                   5007.0          platelets x 1000      222.0
                   5730.0           total bilirubin        0.5
1135185            1031.0          platelets x 1000      106.0
                   2504.0          platelets x 1000      127.0
                   4055.0          platelets x 1000      172.0
                   5461.0          platelets x 1000      217.0
                   6907.0          platelets x 1000      261.0
                   8363.0          platelets x 1000      270.0
1135186           -439.0           platelets x 1000      180.0
                   62.0            platelets x 1000      103.0
                   413.0           platelets x 1000       63.0
                   844.0           platelets x 1000       70.0
                   938.0                       paO2       76.5
                   1104.0          platelets x 1000       72.0
                   1513.0          platelets x 1000       65.0
                   1873.0          platelets x 1000       50.0
                   2119.0          platelets x 1000      101.0
                   2600.0                      paO2      220.0
                   2679.0                      paO2      225.0
                   2998.0                      paO2      158.0
                   3298.0          platelets x 1000       63.0
                   3583.0          platelets x 1000       57.0
                   4213.0          platelets x 1000       53.0
                   4943.0          platelets x 1000       63.0
                   6414.0          platelets x 1000       67.0
                   7823.0          platelets x 1000       79.0

                                  labmeasurenamesystem  \
patientunitstayid labresultoffset
142493             50.0                          K/mcL
                   180.0                         mm Hg
                   237.0                         mm Hg
                   292.0                         K/mcL
                   667.0                         K/mcL
142494             1033.0                        K/mcL
142495            -238.0                         mg/dL

In [20]:
test.to_csv(r'final.csv', sep=',',index=None, header=True)

In [21]:
respiratory=pd.read_csv("respiratoryCharting.csv")

In [25]:
from pyspark.sql import *
df=spark.read.csv('file:////home/ronet/Documents/eicudemochallenge/final.csv',inferSchema = True, header = True)
df.show()

+-----------------+-----------------------+----------------------------+---------------------------+-----------------+---------------+---------+----------------+---------+--------------------+-----------------------+----------------------+
|patientunitstayid|nursingchartentryoffset|nursingchartcelltypevallabel|nursingchartcelltypevalname|nursingchartvalue|labresultoffset|labtypeid|         labname|labresult|labmeasurenamesystem|labmeasurenameinterface|labresultrevisedoffset|
+-----------------+-----------------------+----------------------------+---------------------------+-----------------+---------------+---------+----------------+---------+--------------------+-----------------------+----------------------+
|           142493|                   12.0|          Glasgow coma score|                  GCS Total|             11.0|           50.0|      3.0|platelets x 1000|     65.0|               K/mcL|                  K/mcL|                  70.0|
|           142493|                   12.0|          Glasgow coma score|                  GCS Total|             11.0|          180.0|      7.0|            paO2|    197.0|               mm Hg|                  mm Hg|                 188.0|
|           142493|                   12.0|          Glasgow coma score|                  GCS Total|             11.0|          237.0|      7.0|            paO2|    156.0|               mm Hg|                  mm Hg|                 249.0|
|           142493|                   12.0|          Glasgow coma score|                  GCS Total|             11.0|          292.0|      3.0|platelets x 1000|    120.0|               K/mcL|                  K/mcL|                 299.0|
|           142493|                   12.0|          Glasgow coma score|                  GCS Total|             11.0|          667.0|      3.0|platelets x 1000|    126.0|               K/mcL|                  K/mcL|                 683.0|
|           142493|                  102.0|          Glasgow coma score|                  GCS Total|             10.0|           50.0|      3.0|platelets x 1000|     65.0|               K/mcL|                  K/mcL|                  70.0|
|           142493|                  102.0|          Glasgow coma score|                  GCS Total|             10.0|          180.0|      7.0|            paO2|    197.0|               mm Hg|                  mm Hg|                 188.0|
|           142493|                  102.0|          Glasgow coma score|                  GCS Total|             10.0|          237.0|      7.0|            paO2|    156.0|               mm Hg|                  mm Hg|                 249.0|
|           142493|                  102.0|          Glasgow coma score|                  GCS Total|             10.0|          292.0|      3.0|platelets x 1000|    120.0|               K/mcL|                  K/mcL|                 299.0|
|           142493|                  102.0|          Glasgow coma score|                  GCS Total|             10.0|          667.0|      3.0|platelets x 1000|    126.0|               K/mcL|                  K/mcL|                 683.0|
|           142493|                  342.0|          Glasgow coma score|                  GCS Total|             15.0|           50.0|      3.0|platelets x 1000|     65.0|               K/mcL|                  K/mcL|                  70.0|
|           142493|                  342.0|          Glasgow coma score|                  GCS Total|             15.0|          180.0|      7.0|            paO2|    197.0|               mm Hg|                  mm Hg|                 188.0|
|           142493|                  342.0|          Glasgow coma score|                  GCS Total|             15.0|          237.0|      7.0|            paO2|    156.0|               mm Hg|                  mm Hg|                 249.0|
|           142493|                  342.0|          Glasgow coma score|                  GCS Total|             15.0|          292.0|      3.0|platelets x 1000|    120.0|               K/mcL|                  K/mcL|                 299.0|
|           142493|                  342.0|          Glasgow coma score|                  GCS Total|             15.0|          667.0|      3.0|platelets x 1000|    126.0|               K/mcL|                  K/mcL|                 683.0|
|           142493|                  582.0|          Glasgow coma score|                  GCS Total|             15.0|           50.0|      3.0|platelets x 1000|     65.0|               K/mcL|                  K/mcL|                  70.0|
|           142493|                  582.0|          Glasgow coma score|                  GCS Total|             15.0|          180.0|      7.0|            paO2|    197.0|               mm Hg|                  mm Hg|                 188.0|
|           142493|                  582.0|          Glasgow coma score|                  GCS Total|             15.0|          237.0|      7.0|            paO2|    156.0|               mm Hg|                  mm Hg|                 249.0|
|           142493|                  582.0|          Glasgow coma score|                  GCS Total|             15.0|          292.0|      3.0|platelets x 1000|    120.0|               K/mcL|                  K/mcL|                 299.0|
|           142493|                  582.0|          Glasgow coma score|                  GCS Total|             15.0|          667.0|      3.0|platelets x 1000|    126.0|               K/mcL|                  K/mcL|                 683.0|
+-----------------+-----------------------+----------------------------+---------------------------+-----------------+---------------+---------+----------------+---------+--------------------+-----------------------+----------------------+
only showing top 20 rows