In [1]:
import pandas as pd
import numpy as np

In [2]:
pre_final_lab=pd.read_csv("labs_after_FiO2.csv")

In [3]:
pre_final_lab.head()

,patientunitstayid,labresultoffset,labname,labresult,paO2_FiO2
0,141168,1701,urinary creatinine,173.12,NaN
1,141168,2026,paO2,68.00,136.0
2,141168,2141,paO2,121.00,121.0
3,141168,1133,platelets x 1000,213.00,NaN
4,141168,2010,paO2,42.00,84.0

In [4]:
pre_final_lab['platelets_x_1000']=np.nan
pre_final_lab['total_bilirubin']=np.nan
pre_final_lab['urinary_creatinine']=np.nan

In [5]:
pre_final_lab['platelets_x_1000']=pre_final_lab.loc[pre_final_lab['labname']=='platelets x 1000','labresult']
pre_final_lab['total_bilirubin']=pre_final_lab.loc[pre_final_lab['labname']=='total bilirubin','labresult']
pre_final_lab['urinary_creatinine']=pre_final_lab.loc[pre_final_lab['labname']=='urinary creatinine','labresult']

In [6]:
pre_final_lab

,patientunitstayid,labresultoffset,labname,labresult,paO2_FiO2,platelets_x_1000,total_bilirubin,urinary_creatinine
0,141168,1701,urinary creatinine,173.12,NaN,NaN,NaN,173.12
1,141168,2026,paO2,68.00,136.000000,NaN,NaN,NaN
2,141168,2141,paO2,121.00,121.000000,NaN,NaN,NaN
3,141168,1133,platelets x 1000,213.00,NaN,213.0,NaN,NaN
4,141168,2010,paO2,42.00,84.000000,NaN,NaN,NaN
5,141168,2026,total bilirubin,5.20,NaN,NaN,5.2,NaN
6,141168,2026,platelets x 1000,187.00,NaN,187.0,NaN,NaN
7,141168,1805,paO2,41.00,82.000000,NaN,NaN,NaN
8,141168,516,total bilirubin,2.60,NaN,NaN,2.6,NaN
9,141168,1133,total bilirubin,4.10,NaN,NaN,4.1,NaN
10,141168,516,platelets x 1000,209.00,NaN,209.0,NaN,NaN
11,141178,-280,platelets x 1000,273.00,NaN,273.0,NaN,NaN
12,141178,-280,total bilirubin,0.40,NaN,NaN,0.4,NaN
13,141179,1487,platelets x 1000,219.00,NaN,219.0,NaN,NaN
14,141194,7303,platelets x 1000,139.00,NaN,139.0,NaN,NaN
15,141194,2102,paO2,100.00,263.923680,NaN,NaN,NaN
16,141194,312,total bilirubin,0.40,NaN,NaN,0.4,NaN
17,141194,1630,platelets x 1000,199.00,NaN,199.0,NaN,NaN
18,141194,8762,platelets x 1000,158.00,NaN,158.0,NaN,NaN
19,141194,-923,total bilirubin,0.40,NaN,NaN,0.4,NaN
20,141194,-923,platelets x 1000,298.00,NaN,298.0,NaN,NaN
21,141194,2998,platelets x 1000,146.00,NaN,146.0,NaN,NaN
22,141194,11658,platelets x 1000,265.00,NaN,265.0,NaN,NaN
23,141194,312,platelets x 1000,233.00,NaN,233.0,NaN,NaN
24,141194,4663,platelets x 1000,142.00,NaN,142.0,NaN,NaN
25,141194,10397,platelets x 1000,200.00,NaN,200.0,NaN,NaN
26,141194,5897,platelets x 1000,125.00,NaN,125.0,NaN,NaN
27,141196,3600,total bilirubin,0.30,NaN,NaN,0.3,NaN
28,141196,4987,platelets x 1000,504.00,NaN,504.0,NaN,NaN
29,141196,1030,paO2,70.00,263.944700,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2010809,3353251,-169,paO2,246.00,246.000000,NaN,NaN,NaN
2010810,3353251,11054,paO2,87.00,217.500000,NaN,NaN,NaN
2010811,3353251,9901,paO2,80.00,177.777770,NaN,NaN,NaN
2010812,3353251,-50,paO2,163.00,163.000000,NaN,NaN,NaN
2010813,3353251,1065,paO2,89.00,111.250000,NaN,NaN,NaN
2010814,3353251,2541,platelets x 1000,205.00,NaN,205.0,NaN,NaN
2010815,3353251,1490,platelets x 1000,202.00,NaN,202.0,NaN,NaN
2010816,3353251,-60,total bilirubin,0.50,NaN,NaN,0.5,NaN
2010817,3353251,5459,platelets x 1000,106.00,NaN,106.0,NaN,NaN
2010818,3353251,4510,paO2,72.00,180.000000,NaN,NaN,NaN
2010819,3353251,-60,platelets x 1000,232.00,NaN,232.0,NaN,NaN
2010820,3353251,5598,paO2,68.00,170.000000,NaN,NaN,NaN
2010821,3353251,1127,platelets x 1000,196.00,NaN,196.0,NaN,NaN
2010822,3353251,972,paO2,153.00,191.250000,NaN,NaN,NaN
2010823,3353251,82,paO2,136.00,136.000000,NaN,NaN,NaN
2010824,3353251,6868,platelets x 1000,129.00,NaN,129.0,NaN,NaN
2010825,3353251,2448,paO2,71.00,118.333336,NaN,NaN,NaN
2010826,3353251,310,paO2,94.00,94.000000,NaN,NaN,NaN
2010827,3353254,5558,platelets x 1000,185.00,NaN,185.0,NaN,NaN
2010828,3353254,-256,platelets x 1000,268.00,NaN,268.0,NaN,NaN
2010829,3353254,-256,total bilirubin,0.40,NaN,NaN,0.4,NaN
2010830,3353254,4237,paO2,57.00,inf,NaN,NaN,NaN
2010831,3353254,1218,platelets x 1000,183.00,NaN,183.0,NaN,NaN
2010832,3353254,2610,platelets x 1000,132.00,NaN,132.0,NaN,NaN
2010833,3353254,4143,platelets x 1000,158.00,NaN,158.0,NaN,NaN
2010834,3353263,7490,platelets x 1000,246.00,NaN,246.0,NaN,NaN
2010835,3353263,3048,platelets x 1000,180.00,NaN,180.0,NaN,NaN
2010836,3353263,-7,platelets x 1000,161.00,NaN,161.0,NaN,NaN
2010837,3353263,-7,platelets x 1000,164.00,NaN,164.0,NaN,NaN
2010838,3353263,1733,platelets x 1000,169.00,NaN,169.0,NaN,NaN

In [7]:
pre_final_lab['paO2_FiO2']=pre_final_lab['paO2_FiO2'].astype('float32')
pre_final_lab['platelets_x_1000']=pre_final_lab['platelets_x_1000'].astype('float32')
pre_final_lab['total_bilirubin']=pre_final_lab['total_bilirubin'].astype('float32')
pre_final_lab['urinary_creatinine']=pre_final_lab['urinary_creatinine'].astype('float32')

In [8]:
pre_final_lab.dtypes

patientunitstayid       int64
labresultoffset         int64
labname                object
labresult             float64
paO2_FiO2             float32
platelets_x_1000      float32
total_bilirubin       float32
urinary_creatinine    float32
dtype: object

In [9]:
pre_final_lab=pre_final_lab.replace([np.inf, -np.inf], np.nan)

In [10]:
del pre_final_lab['labresult']

In [11]:
pre_final_lab

,patientunitstayid,labresultoffset,labname,paO2_FiO2,platelets_x_1000,total_bilirubin,urinary_creatinine
0,141168,1701,urinary creatinine,NaN,NaN,NaN,173.119995
1,141168,2026,paO2,136.000000,NaN,NaN,NaN
2,141168,2141,paO2,121.000000,NaN,NaN,NaN
3,141168,1133,platelets x 1000,NaN,213.0,NaN,NaN
4,141168,2010,paO2,84.000000,NaN,NaN,NaN
5,141168,2026,total bilirubin,NaN,NaN,5.2,NaN
6,141168,2026,platelets x 1000,NaN,187.0,NaN,NaN
7,141168,1805,paO2,82.000000,NaN,NaN,NaN
8,141168,516,total bilirubin,NaN,NaN,2.6,NaN
9,141168,1133,total bilirubin,NaN,NaN,4.1,NaN
10,141168,516,platelets x 1000,NaN,209.0,NaN,NaN
11,141178,-280,platelets x 1000,NaN,273.0,NaN,NaN
12,141178,-280,total bilirubin,NaN,NaN,0.4,NaN
13,141179,1487,platelets x 1000,NaN,219.0,NaN,NaN
14,141194,7303,platelets x 1000,NaN,139.0,NaN,NaN
15,141194,2102,paO2,263.923676,NaN,NaN,NaN
16,141194,312,total bilirubin,NaN,NaN,0.4,NaN
17,141194,1630,platelets x 1000,NaN,199.0,NaN,NaN
18,141194,8762,platelets x 1000,NaN,158.0,NaN,NaN
19,141194,-923,total bilirubin,NaN,NaN,0.4,NaN
20,141194,-923,platelets x 1000,NaN,298.0,NaN,NaN
21,141194,2998,platelets x 1000,NaN,146.0,NaN,NaN
22,141194,11658,platelets x 1000,NaN,265.0,NaN,NaN
23,141194,312,platelets x 1000,NaN,233.0,NaN,NaN
24,141194,4663,platelets x 1000,NaN,142.0,NaN,NaN
25,141194,10397,platelets x 1000,NaN,200.0,NaN,NaN
26,141194,5897,platelets x 1000,NaN,125.0,NaN,NaN
27,141196,3600,total bilirubin,NaN,NaN,0.3,NaN
28,141196,4987,platelets x 1000,NaN,504.0,NaN,NaN
29,141196,1030,paO2,263.944702,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2010809,3353251,-169,paO2,246.000000,NaN,NaN,NaN
2010810,3353251,11054,paO2,217.500000,NaN,NaN,NaN
2010811,3353251,9901,paO2,177.777771,NaN,NaN,NaN
2010812,3353251,-50,paO2,163.000000,NaN,NaN,NaN
2010813,3353251,1065,paO2,111.250000,NaN,NaN,NaN
2010814,3353251,2541,platelets x 1000,NaN,205.0,NaN,NaN
2010815,3353251,1490,platelets x 1000,NaN,202.0,NaN,NaN
2010816,3353251,-60,total bilirubin,NaN,NaN,0.5,NaN
2010817,3353251,5459,platelets x 1000,NaN,106.0,NaN,NaN
2010818,3353251,4510,paO2,180.000000,NaN,NaN,NaN
2010819,3353251,-60,platelets x 1000,NaN,232.0,NaN,NaN
2010820,3353251,5598,paO2,170.000000,NaN,NaN,NaN
2010821,3353251,1127,platelets x 1000,NaN,196.0,NaN,NaN
2010822,3353251,972,paO2,191.250000,NaN,NaN,NaN
2010823,3353251,82,paO2,136.000000,NaN,NaN,NaN
2010824,3353251,6868,platelets x 1000,NaN,129.0,NaN,NaN
2010825,3353251,2448,paO2,118.333336,NaN,NaN,NaN
2010826,3353251,310,paO2,94.000000,NaN,NaN,NaN
2010827,3353254,5558,platelets x 1000,NaN,185.0,NaN,NaN
2010828,3353254,-256,platelets x 1000,NaN,268.0,NaN,NaN
2010829,3353254,-256,total bilirubin,NaN,NaN,0.4,NaN
2010830,3353254,4237,paO2,NaN,NaN,NaN,NaN
2010831,3353254,1218,platelets x 1000,NaN,183.0,NaN,NaN
2010832,3353254,2610,platelets x 1000,NaN,132.0,NaN,NaN
2010833,3353254,4143,platelets x 1000,NaN,158.0,NaN,NaN
2010834,3353263,7490,platelets x 1000,NaN,246.0,NaN,NaN
2010835,3353263,3048,platelets x 1000,NaN,180.0,NaN,NaN
2010836,3353263,-7,platelets x 1000,NaN,161.0,NaN,NaN
2010837,3353263,-7,platelets x 1000,NaN,164.0,NaN,NaN
2010838,3353263,1733,platelets x 1000,NaN,169.0,NaN,NaN

In [12]:
pre_final_lab.describe()

,patientunitstayid,labresultoffset,paO2_FiO2,platelets_x_1000,total_bilirubin,urinary_creatinine
count,2.010839e+06,2.010839e+06,190301.000000,1.139619e+06,425009.000000,13227.000000
mean,1.753460e+06,5.185645e+03,388.938141,2.157587e+02,1.558491,99.160881
std,1.003857e+06,3.606784e+04,2225.018311,1.208638e+02,3.583854,71.979446
min,1.411680e+05,-4.731957e+07,-212.500000,0.000000e+00,0.000000,0.400000
25%,9.594120e+05,1.070000e+02,137.500000,1.370000e+02,0.400000,48.000000
50%,1.644075e+06,2.125000e+03,214.285721,1.970000e+02,0.600000,82.839996
75%,2.770721e+06,6.822000e+03,316.666656,2.700000e+02,1.200000,130.555000
max,3.353263e+06,8.305830e+05,129666.664062,3.092000e+03,99.000000,1288.000000

<h1>Can be done</h1>
pre_final_lab['paO2_FiO2']=pre_final_lab['paO2_FiO2'].ffill(limit=5)
pre_final_lab['platelets_x_1000']=pre_final_lab['platelets_x_1000'].ffill(limit=5)
pre_final_lab['total_bilirubin']=pre_final_lab['total_bilirubin'].ffill(limit=5)
pre_final_lab['urinary_creatinine']=pre_final_lab['urinary_creatinine'].ffill(limit=5)
pre_final_lab['paO2_FiO2']=pre_final_lab['paO2_FiO2'].bfill(limit=5)
pre_final_lab['platelets_x_1000']=pre_final_lab['platelets_x_1000'].bfill(limit=5)
pre_final_lab['total_bilirubin']=pre_final_lab['total_bilirubin'].bfill(limit=5)
pre_final_lab['urinary_creatinine']=pre_final_lab['urinary_creatinine'].bfill(limit=5)

In [13]:
del pre_final_lab['labname']

In [14]:
pre_final_lab.head()

,patientunitstayid,labresultoffset,paO2_FiO2,platelets_x_1000,total_bilirubin,urinary_creatinine
0,141168,1701,NaN,NaN,NaN,173.119995
1,141168,2026,136.0,NaN,NaN,NaN
2,141168,2141,121.0,NaN,NaN,NaN
3,141168,1133,NaN,213.0,NaN,NaN
4,141168,2010,84.0,NaN,NaN,NaN

In [15]:
pre_final_lab.to_csv('labs_updated.csv',sep=',',index=False,encoding='utf-8')

<h4>Adding additional parameters from physionet challenge data</h4>

In [14]:
df_lab=pd.read_csv('lab.csv',chunksize=10000)

In [15]:
arr=[]
for chunk in df_lab:
    arr.append(chunk)

In [16]:
df_lab=pd.concat(arr,sort=False)

In [17]:
df_lab.head()

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
0,52307161,141168,2026,3,fibrinogen,177.0,177,mg/dL,mg/dL,2219
1,50363251,141168,1133,3,PT - INR,2.5,2.5,ratio,NaN,1208
2,49149139,141168,2026,1,magnesium,2.0,2.0,mg/dL,mg/dL,2090
3,50363250,141168,1133,3,PT,26.6,26.6,sec,sec,1208
4,66695374,141168,2141,7,pH,7.2,7.20,NaN,Units,2155

In [16]:
df_lab.loc[df_lab['labname'].str.contains('HCO3')]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
10,66695368,141168,2141,7,HCO3,14.0,14,mmol/L,mmol/L,2155
26,67217619,141168,1805,7,HCO3,15.0,15,mmol/L,mmol/L,1811
27,67301506,141168,2026,7,HCO3,11.0,11,mmol/L,mmol/L,2054
33,67446285,141168,2010,7,HCO3,14.0,14,mmol/L,mmol/L,2026
358,66794219,141194,2102,7,HCO3,13.0,13,mmol/L,mmol/L,2114
567,67254139,141196,1030,7,HCO3,30.0,30,mmol/L,mmol/L,1052
723,68006052,141203,1,7,HCO3,25.0,25,mmol/L,mmol/L,11
819,67758200,141227,-13,7,HCO3,11.0,11,mmol/L,mmol/L,-5
852,67461631,141227,1647,7,HCO3,18.0,18,mmol/L,mmol/L,1661
862,66963367,141227,612,7,HCO3,16.0,16,mmol/L,mmol/L,620
928,66928001,141227,982,7,HCO3,15.0,15,mmol/L,mmol/L,1013
1033,67846511,141229,74,7,HCO3,29.0,29,mmol/L,mmol/L,84
1057,68276422,141233,-148,7,HCO3,23.0,23,mmol/L,mmol/L,-139
1092,67187043,141233,-248,7,HCO3,23.0,23,mmol/L,mmol/L,-238
1112,66633574,141233,278,7,HCO3,19.0,19,mmol/L,mmol/L,1678
1120,67722097,141233,-267,7,HCO3,21.0,21,mmol/L,mmol/L,-254
1145,66882133,141233,92,7,HCO3,20.0,20,mmol/L,mmol/L,1675
1195,68200025,141233,388,7,HCO3,18.0,18,mmol/L,mmol/L,404
1246,67240777,141233,-85,7,HCO3,22.0,22,mmol/L,mmol/L,1673
1247,68069422,141233,2857,7,HCO3,23.0,23,mmol/L,mmol/L,2879
1255,66792143,141233,2026,7,HCO3,23.0,23,mmol/L,mmol/L,2032
1271,67432972,141233,1419,7,HCO3,22.0,22,mmol/L,mmol/L,1431
1281,67088852,141233,2263,7,HCO3,23.0,23,mmol/L,mmol/L,2269
1322,66994758,141233,1062,7,HCO3,21.0,21,mmol/L,mmol/L,1077
1325,68212244,141233,-355,7,HCO3,23.0,23,mmol/L,mmol/L,-346
1370,67347331,141233,6747,7,HCO3,20.0,20,mmol/L,mmol/L,6767
1373,67821800,141233,1537,7,HCO3,24.0,24,mmol/L,mmol/L,1546
1428,66789638,141233,2457,7,HCO3,23.0,23,mmol/L,mmol/L,2474
1485,67336414,141233,-103,7,HCO3,23.0,23,mmol/L,mmol/L,1654
1512,68265142,141233,1762,7,HCO3,24.0,24,mmol/L,mmol/L,1772
...,...,...,...,...,...,...,...,...,...,...
39130898,829267836,3353216,785,7,HCO3,20.0,20.0,mmol/L,mmol/L,785
39130904,828941939,3353216,16,7,HCO3,20.0,20.0,mmol/L,mmol/L,16
39130930,829918425,3353216,183,7,HCO3,18.7,18.7,mmol/L,mmol/L,183
39130947,829380550,3353216,1208,7,HCO3,19.6,19.6,mmol/L,mmol/L,1208
39131036,829943061,3353226,5127,7,HCO3,23.6,23.6,mmol/L,mmol/L,5127
39131103,829452199,3353226,8048,7,HCO3,23.8,23.8,mmol/L,mmol/L,8048
39131133,829720074,3353226,-135,7,HCO3,30.2,30.2,mmol/L,mmol/L,-135
39131134,829727645,3353226,3707,7,HCO3,24.6,24.6,mmol/L,mmol/L,3707
39131167,829159677,3353226,2283,7,HCO3,25.1,25.1,mmol/L,mmol/L,2283
39131170,828923494,3353226,3812,7,HCO3,24.3,24.3,mmol/L,mmol/L,3812
39131179,829356071,3353226,912,7,HCO3,29.0,29.0,mmol/L,mmol/L,912
39131189,829662136,3353226,-213,7,HCO3,30.5,30.5,mmol/L,mmol/L,-213
39131233,829263777,3353226,6559,7,HCO3,24.7,24.7,mmol/L,mmol/L,6559
39131261,828992365,3353226,9424,7,HCO3,25.6,25.6,mmol/L,mmol/L,9424
39131281,829315928,3353226,4029,7,HCO3,23.6,23.6,mmol/L,mmol/L,4029
39131681,829488893,3353251,428,7,HCO3,18.2,18.2,mmol/L,mmol/L,428
39131713,829411597,3353251,-50,7,HCO3,15.5,15.5,mmol/L,mmol/L,-50
39131781,829493600,3353251,-169,7,HCO3,16.2,16.2,mmol/L,mmol/L,-169
39131789,829836625,3353251,-144,7,HCO3,20.5,20.5,mmol/L,mmol/L,-144
39131894,829261269,3353251,9901,7,HCO3,29.2,29.2,mmol/L,mmol/L,9901
39131924,829883654,3353251,3864,7,HCO3,28.5,28.5,mmol/L,mmol/L,3864
39131932,829768482,3353251,1065,7,HCO3,24.4,24.4,mmol/L,mmol/L,1065
39131935,829909890,3353251,310,7,HCO3,16.6,16.6,mmol/L,mmol/L,310
39132004,829814900,3353251,11054,7,HCO3,32.5,32.5,mmol/L,mmol/L,11054
39132042,830007176,3353251,5598,7,HCO3,28.9,28.9,mmol/L,mmol/L,5598
39132102,828968819,3353251,4510,7,HCO3,29.9,29.9,mmol/L,mmol/L,4510
39132193,829612136,3353251,2448,7,HCO3,27.3,27.3,mmol/L,mmol/L,2448
39132197,829361093,3353251,972,7,HCO3,24.2,24.2,mmol/L,mmol/L,972
39132211,829742567,3353251,82,7,HCO3,12.4,12.4,mmol/L,mmol/L,82
39132363,829249133,3353254,4237,7,HCO3,21.8,21.8,mmol/L,mmol/L,4237

In [17]:
df_lab.loc[df_lab['labname'].str.contains('pH')]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
4,66695374,141168,2141,7,pH,7.200,7.20,NaN,Units,2155
48,67446290,141168,2010,7,pH,7.140,7.14,NaN,Units,2026
51,67301510,141168,2026,7,pH,7.160,7.16,NaN,Units,2054
53,67217624,141168,1805,7,pH,7.140,7.14,NaN,Units,1811
364,66794224,141194,2102,7,pH,7.310,7.31,NaN,Units,2114
573,67254136,141196,1030,7,pH,7.430,7.43,NaN,Units,1052
733,68006056,141203,1,7,pH,7.450,7.45,NaN,Units,11
831,67758204,141227,-13,7,pH,7.370,7.37,NaN,Units,-5
854,66928006,141227,982,7,pH,7.400,7.40,NaN,Units,1013
868,66963372,141227,612,7,pH,7.460,7.46,NaN,Units,620
892,67461636,141227,1647,7,pH,7.240,7.24,NaN,Units,1661
1041,67846514,141229,74,7,pH,7.360,7.36,NaN,Units,84
1065,68276426,141233,-148,7,pH,7.380,7.38,NaN,Units,-139
1072,67722101,141233,-267,7,pH,7.440,7.44,NaN,Units,-254
1127,66882138,141233,92,7,pH,7.390,7.39,NaN,Units,1675
1128,67187047,141233,-248,7,pH,7.400,7.40,NaN,Units,-238
1136,66633579,141233,278,7,pH,7.390,7.39,NaN,Units,1678
1226,67347336,141233,6747,7,pH,7.420,7.42,NaN,Units,6767
1241,67088857,141233,2263,7,pH,7.440,7.44,NaN,Units,2269
1243,68200030,141233,388,7,pH,7.380,7.38,NaN,Units,404
1258,66994763,141233,1062,7,pH,7.410,7.41,NaN,Units,1077
1313,68212248,141233,-355,7,pH,7.400,7.40,NaN,Units,-346
1342,67240781,141233,-85,7,pH,7.420,7.42,NaN,Units,1673
1365,67336418,141233,-103,7,pH,7.450,7.45,NaN,Units,1654
1387,66792148,141233,2026,7,pH,7.440,7.44,NaN,Units,2032
1389,67821805,141233,1537,7,pH,7.430,7.43,NaN,Units,1546
1420,66789643,141233,2457,7,pH,7.440,7.44,NaN,Units,2474
1439,68069427,141233,2857,7,pH,7.400,7.40,NaN,Units,2879
1445,67370594,141233,24,7,pH,7.340,7.34,NaN,Units,1675
1455,67432977,141233,1419,7,pH,7.400,7.40,NaN,Units,1431
...,...,...,...,...,...,...,...,...,...,...
39130912,828941945,3353216,16,7,pH,7.185,7.185,NaN,NaN,16
39130918,829223006,3353216,183,7,pH,7.293,7.293,NaN,NaN,183
39130956,829267842,3353216,785,7,pH,7.368,7.368,NaN,NaN,785
39130971,829380554,3353216,1208,7,pH,7.356,7.356,NaN,NaN,1208
39131122,829776823,3353226,5127,7,pH,7.230,7.230,NaN,NaN,5127
39131127,829356077,3353226,912,7,pH,7.280,7.280,NaN,NaN,912
39131138,829727651,3353226,3707,7,pH,7.236,7.236,NaN,NaN,3707
39131149,829662140,3353226,-213,7,pH,7.180,7.180,NaN,NaN,-213
39131155,829159683,3353226,2283,7,pH,7.300,7.300,NaN,NaN,2283
39131159,829452205,3353226,8048,7,pH,7.280,7.280,NaN,NaN,8048
39131181,829720080,3353226,-135,7,pH,7.283,7.283,NaN,NaN,-135
39131185,829263783,3353226,6559,7,pH,7.281,7.281,NaN,NaN,6559
39131218,828923500,3353226,3812,7,pH,7.239,7.239,NaN,NaN,3812
39131253,828992371,3353226,9424,7,pH,7.303,7.303,NaN,NaN,9424
39131279,829315934,3353226,4029,7,pH,7.252,7.252,NaN,NaN,4029
39131649,829488899,3353251,428,7,pH,7.224,7.224,NaN,NaN,428
39131805,829836631,3353251,-144,7,pH,7.182,7.182,NaN,NaN,-144
39131828,829883660,3353251,3864,7,pH,7.467,7.467,NaN,NaN,3864
39131829,829493606,3353251,-169,7,pH,6.973,6.973,NaN,NaN,-169
39131865,829411603,3353251,-50,7,pH,7.231,7.231,NaN,NaN,-50
39131926,829261275,3353251,9901,7,pH,7.405,7.405,NaN,NaN,9901
39131948,829814906,3353251,11054,7,pH,7.412,7.412,NaN,NaN,11054
39131980,829768488,3353251,1065,7,pH,7.559,7.559,NaN,NaN,1065
39132113,830007182,3353251,5598,7,pH,7.497,7.497,NaN,NaN,5598
39132131,829361099,3353251,972,7,pH,7.614,7.614,NaN,NaN,972
39132135,829742573,3353251,82,7,pH,7.161,7.161,NaN,NaN,82
39132169,828968825,3353251,4510,7,pH,7.479,7.479,NaN,NaN,4510
39132221,829612142,3353251,2448,7,pH,7.405,7.405,NaN,NaN,2448
39132260,829194475,3353251,310,7,pH,7.194,7.194,NaN,NaN,310
39132357,829249130,3353254,4237,7,pH,7.412,7.412,NaN,NaN,4237

In [20]:
df_lab.loc[df_lab['labname'].str.contains('paCO2',case=False)]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
39,67446289,141168,2010,7,paCO2,44.0,44,mm Hg,mm Hg,2026
40,66695373,141168,2141,7,paCO2,37.0,37,mm Hg,mm Hg,2155
42,67301509,141168,2026,7,paCO2,31.0,31,mm Hg,mm Hg,2054
77,67217623,141168,1805,7,paCO2,46.0,46,mm Hg,mm Hg,1811
362,66794223,141194,2102,7,paCO2,26.0,26,mm Hg,mm Hg,2114
579,67254137,141196,1030,7,paCO2,45.0,45,mm Hg,mm Hg,1052
699,68006055,141203,1,7,paCO2,37.0,37,mm Hg,mm Hg,11
827,67758203,141227,-13,7,paCO2,20.0,20,mm Hg,mm Hg,-5
867,67461635,141227,1647,7,paCO2,43.0,43,mm Hg,mm Hg,1661
871,66963371,141227,612,7,paCO2,23.0,23,mm Hg,mm Hg,620
934,66928005,141227,982,7,paCO2,24.0,24,mm Hg,mm Hg,1013
1037,67846513,141229,74,7,paCO2,52.0,52,mm Hg,mm Hg,84
1060,67722100,141233,-267,7,paCO2,29.0,29,mm Hg,mm Hg,-254
1061,68276425,141233,-148,7,paCO2,41.0,41,mm Hg,mm Hg,-139
1133,66882137,141233,92,7,paCO2,30.0,30,mm Hg,mm Hg,1675
1140,67187046,141233,-248,7,paCO2,38.0,38,mm Hg,mm Hg,-238
1148,66633578,141233,278,7,paCO2,28.0,28,mm Hg,mm Hg,1678
1215,67432976,141233,1419,7,paCO2,37.0,37,mm Hg,mm Hg,1431
1222,67240780,141233,-85,7,paCO2,33.0,33,mm Hg,mm Hg,1673
1235,68200029,141233,388,7,paCO2,31.0,31,mm Hg,mm Hg,404
1267,66792147,141233,2026,7,paCO2,33.0,33,mm Hg,mm Hg,2032
1289,67088856,141233,2263,7,paCO2,33.0,33,mm Hg,mm Hg,2269
1290,66994762,141233,1062,7,paCO2,33.0,33,mm Hg,mm Hg,1077
1309,68212247,141233,-355,7,paCO2,37.0,37,mm Hg,mm Hg,-346
1338,67347335,141233,6747,7,paCO2,31.0,31,mm Hg,mm Hg,6767
1381,67370593,141233,24,7,paCO2,33.0,33,mm Hg,mm Hg,1675
1405,67821804,141233,1537,7,paCO2,36.0,36,mm Hg,mm Hg,1546
1460,66789642,141233,2457,7,paCO2,35.0,35,mm Hg,mm Hg,2474
1471,68069426,141233,2857,7,paCO2,37.0,37,mm Hg,mm Hg,2879
1500,68265145,141233,1762,7,paCO2,36.0,36,mm Hg,mm Hg,1772
...,...,...,...,...,...,...,...,...,...,...
39130892,828941944,3353216,16,7,paCO2,53.1,53.1,mm Hg,mmHg,16
39130894,829918430,3353216,183,7,paCO2,38.7,38.7,mm Hg,mmHg,183
39130948,829267841,3353216,785,7,paCO2,34.7,34.7,mm Hg,mmHg,785
39130955,829380553,3353216,1208,7,paCO2,35.1,35.1,mm Hg,mmHg,1208
39131028,829727650,3353226,3707,7,paCO2,57.9,57.9,mm Hg,mmHg,3707
39131086,829776822,3353226,5127,7,paCO2,56.3,56.3,mm Hg,mmHg,5127
39131111,829356076,3353226,912,7,paCO2,61.7,61.7,mm Hg,mmHg,912
39131119,829452204,3353226,8048,7,paCO2,50.8,50.8,mm Hg,mmHg,8048
39131165,829720079,3353226,-135,7,paCO2,63.7,63.7,mm Hg,mmHg,-135
39131175,829159682,3353226,2283,7,paCO2,51.1,51.1,mm Hg,mmHg,2283
39131201,828992370,3353226,9424,7,paCO2,51.7,51.7,mm Hg,mmHg,9424
39131210,828923499,3353226,3812,7,paCO2,56.7,56.7,mm Hg,mmHg,3812
39131229,829662139,3353226,-213,7,paCO2,81.7,81.7,mm Hg,mmHg,-213
39131247,829263782,3353226,6559,7,paCO2,52.5,52.5,mm Hg,mmHg,6559
39131291,829315933,3353226,4029,7,paCO2,53.6,53.6,mm Hg,mmHg,4029
39131665,829488898,3353251,428,7,paCO2,44.0,44.0,mm Hg,mmHg,428
39131737,829493605,3353251,-169,7,paCO2,69.7,69.7,mm Hg,mmHg,-169
39131804,829883659,3353251,3864,7,paCO2,39.4,39.4,mm Hg,mmHg,3864
39131833,829411602,3353251,-50,7,paCO2,36.9,36.9,mm Hg,mmHg,-50
39131844,829768487,3353251,1065,7,paCO2,26.4,26.4,mm Hg,mmHg,1065
39131860,829814905,3353251,11054,7,paCO2,51.1,51.1,mm Hg,mmHg,11054
39131869,829836630,3353251,-144,7,paCO2,54.7,54.7,mm Hg,mmHg,-144
39131878,829261274,3353251,9901,7,paCO2,46.6,46.6,mm Hg,mmHg,9901
39132034,828968824,3353251,4510,7,paCO2,40.3,40.3,mm Hg,mmHg,4510
39132115,829612141,3353251,2448,7,paCO2,43.6,43.6,mm Hg,mmHg,2448
39132161,830007181,3353251,5598,7,paCO2,37.4,37.4,mm Hg,mmHg,5598
39132183,829742572,3353251,82,7,paCO2,34.8,34.8,mm Hg,mmHg,82
39132205,829361098,3353251,972,7,paCO2,23.2,23.2,mm Hg,mmHg,972
39132256,829194474,3353251,310,7,paCO2,43.1,43.1,mm Hg,mmHg,310
39132360,829249131,3353254,4237,7,paCO2,34.3,34.3,mm Hg,mmHg,4237

In [21]:
df_lab.loc[df_lab['labname'].str.contains('SaO2',case=False)]

Empty DataFrame
Columns: [labid, patientunitstayid, labresultoffset, labtypeid, labname, labresult, labresulttext, labmeasurenamesystem, labmeasurenameinterface, labresultrevisedoffset]
Index: []

In [22]:
df_lab.loc[df_lab['labname'].str.contains('direct',case=False)]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
353,48502706,141194,-923,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-894
808,47993021,141208,-139,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-112
2962,46021321,141296,-1827,1,direct bilirubin,0.3,0.3,mg/dL,mg/dL,-1507
4484,43191999,141362,-2342,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,-2319
6807,49172879,141515,6935,1,direct bilirubin,1.0,1.0,mg/dL,mg/dL,6982
6827,49145666,141515,1145,1,direct bilirubin,0.7,0.7,mg/dL,mg/dL,1575
7358,45786399,141548,1289,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,1431
10023,48324378,141590,-135,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-67
11127,49218719,141650,30711,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,30783
11259,45894823,141650,-110,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,-60
13184,46272328,141751,8957,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,9053
16789,48299643,141844,-3277,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,-3250
19352,46845472,141959,-110,1,direct bilirubin,0.3,0.3,mg/dL,mg/dL,-70
21091,46829326,142002,3392,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,3430
21148,49714890,142002,2057,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,2096
22804,45081154,142153,-17907,1,direct bilirubin,0.4,0.4,mg/dL,mg/dL,-17433
22825,47581283,142153,3658,1,direct bilirubin,4.0,4.0,mg/dL,mg/dL,3714
23182,46099165,142153,5133,1,direct bilirubin,5.8,5.8,mg/dL,mg/dL,5268
23201,46529959,142153,2583,1,direct bilirubin,5.2,5.2,mg/dL,mg/dL,2650
23363,43394699,142153,6598,1,direct bilirubin,10.9,10.9,mg/dL,mg/dL,6659
23521,43991414,142173,19399,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,19431
24185,45430910,142173,17970,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,18600
27470,48636108,142483,18240,1,direct bilirubin,0.3,0.3,mg/dL,mg/dL,18354
28280,49295035,142483,21150,1,direct bilirubin,0.3,0.3,mg/dL,mg/dL,21193
29198,45524280,142529,1161,1,direct bilirubin,NaN,<0.1,mg/dL,mg/dL,1233
29204,44506964,142529,-183,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-127
29221,46066006,142529,1870,1,direct bilirubin,NaN,<0.1,mg/dL,mg/dL,1927
29266,46911916,142529,2433,1,direct bilirubin,NaN,<0.1,mg/dL,mg/dL,2759
29268,44532228,142529,416,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,451
31184,48382776,142623,4574,1,direct bilirubin,NaN,<0.1,mg/dL,mg/dL,4751
...,...,...,...,...,...,...,...,...,...,...
39121780,823238832,3353065,-377,1,direct bilirubin,0.0,0.0,mg/dL,mg/dL,-329
39121907,822954395,3353077,12564,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,12590
39122117,823784778,3353077,15450,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,15543
39122304,822355690,3353087,1365,1,direct bilirubin,1.9,1.9,mg/dL,mg/dL,1401
39122624,823214060,3353089,2494,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,2527
39123601,822315809,3353097,7588,1,direct bilirubin,1.9,1.9,mg/dL,mg/dL,7615
39123660,824010240,3353097,325,1,direct bilirubin,3.2,3.2,mg/dL,mg/dL,372
39124158,823150353,3353116,14800,1,direct bilirubin,0.5,0.5,mg/dL,mg/dL,14840
39124408,823332873,3353116,5146,1,direct bilirubin,0.8,0.8,mg/dL,mg/dL,5188
39125202,823348551,3353117,6010,1,direct bilirubin,0.8,0.8,mg/dL,mg/dL,6056
39125327,822321498,3353121,-339,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-292
39125403,823237205,3353127,-3843,1,direct bilirubin,0.5,0.5,mg/dL,mg/dL,-3765
39125870,822944651,3353144,3185,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,3218
39126134,824204504,3353145,256,1,direct bilirubin,0.4,0.4,mg/dL,mg/dL,288
39126262,823703108,3353147,901,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,945
39126273,823189207,3353147,122,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,146
39126288,822967942,3353147,676,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,710
39126444,824227371,3353184,575,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,608
39126858,822452744,3353194,-126,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-34
39126860,822533930,3353194,1640,1,direct bilirubin,1.2,1.2,mg/dL,mg/dL,1686
39127023,822738169,3353196,4698,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,4735
39127211,823003326,3353197,-1790,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,-1752
39127381,822228458,3353197,15000,1,direct bilirubin,0.6,0.6,mg/dL,mg/dL,15036
39129139,823491807,3353198,32397,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,32442
39129307,824120067,3353198,4928,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,4963
39129887,822938036,3353200,29331,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,29378
39130801,823878150,3353213,3000,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,3026
39131188,822674532,3353226,726,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,764
39131822,822755455,3353251,-60,1,direct bilirubin,0.2,0.2,mg/dL,mg/dL,1
39132300,822427683,3353254,-256,1,direct bilirubin,0.1,0.1,mg/dL,mg/dL,-221

In [23]:
df_lab.loc[df_lab['labname'].str.contains('excess',case=False)]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
548,67254140,141196,1030,7,Base Excess,5.0,5,mEq/L,mmol/L,1052
664,68006057,141203,1,7,Base Excess,2.0,2,mEq/L,mmol/L,11
1025,67846515,141229,74,7,Base Excess,3.0,3,mEq/L,mmol/L,84
1508,68265147,141233,1762,7,Base Excess,0.0,0,mEq/L,mmol/L,1772
1779,67955060,141244,-573,7,Base Excess,4.0,4,mEq/L,mmol/L,-565
1880,67647506,141244,-527,7,Base Excess,0.0,0,mEq/L,mmol/L,-518
1887,67608861,141244,-658,7,Base Excess,2.0,2,mEq/L,mmol/L,-649
1894,68193664,141244,-798,7,Base Excess,1.0,1,mEq/L,mmol/L,-789
2347,67678973,141266,-613,7,Base Excess,2.0,2,mEq/L,mmol/L,-601
2386,67342654,141266,-398,7,Base Excess,4.0,4,mEq/L,mmol/L,-358
2646,67192499,141276,11,7,Base Excess,3.0,3,mEq/L,mmol/L,56
2933,68136707,141289,625,7,Base Excess,4.0,4,mEq/L,mmol/L,668
3135,67584195,141296,8,7,Base Excess,5.0,5,mEq/L,mmol/L,24
3163,67616512,141297,1513,7,Base Excess,2.0,2,mEq/L,mmol/L,1530
3298,66690210,141304,-122,7,Base Excess,6.0,6,mEq/L,mmol/L,-108
3415,66676525,141304,458,7,Base Excess,0.0,0,mEq/L,mmol/L,468
3563,67101746,141313,310,7,Base Excess,27.0,27,mEq/L,mmol/L,318
3611,68216058,141314,438,7,Base Excess,4.0,4,mEq/L,mmol/L,446
4621,67482515,141366,-343,7,Base Excess,1.0,1,mEq/L,mmol/L,-322
4814,67553091,141392,-419,7,Base Excess,0.0,0,mEq/L,mmol/L,-413
4861,67266239,141392,5038,7,Base Excess,9.0,9,mEq/L,mmol/L,5054
5449,67048882,141436,-145,7,Base Excess,5.0,5,mEq/L,mmol/L,-135
6047,66647388,141462,1891,7,Base Excess,1.0,1,mEq/L,mmol/L,1898
6108,68187516,141462,-175,7,Base Excess,4.0,4,mEq/L,mmol/L,-165
6156,67462469,141462,1837,7,Base Excess,2.0,2,mEq/L,mmol/L,1845
7796,68100825,141564,-84,7,Base Excess,1.0,1,mEq/L,mmol/L,-74
8285,68158049,141584,692,7,Base Excess,11.0,11,mEq/L,mmol/L,713
8376,67769500,141584,682,7,Base Excess,11.0,11,mEq/L,mmol/L,690
8387,66717459,141584,258,7,Base Excess,12.0,12,mEq/L,mmol/L,270
8399,67589031,141584,-264,7,Base Excess,15.0,15,mEq/L,mmol/L,-260
...,...,...,...,...,...,...,...,...,...,...
39130882,828941949,3353216,16,7,Base Excess,-8.0,-8.0,mEq/L,mmol/L,16
39130886,829223010,3353216,183,7,Base Excess,-8.0,-8.0,mEq/L,mmol/L,183
39130931,829380559,3353216,1208,7,Base Excess,-6.0,-6.0,mEq/L,mmol/L,1208
39130952,829267846,3353216,785,7,Base Excess,-5.0,-5.0,mEq/L,mmol/L,785
39131107,829452209,3353226,8048,7,Base Excess,-3.0,-3.0,mEq/L,mmol/L,8048
39131110,829776827,3353226,5127,7,Base Excess,-4.0,-4.0,mEq/L,mmol/L,5127
39131117,829662145,3353226,-213,7,Base Excess,2.0,2.0,mEq/L,mmol/L,-213
39131130,829727655,3353226,3707,7,Base Excess,-3.0,-3.0,mEq/L,mmol/L,3707
39131148,828923504,3353226,3812,7,Base Excess,-3.0,-3.0,mEq/L,mmol/L,3812
39131151,829159687,3353226,2283,7,Base Excess,-1.0,-1.0,mEq/L,mmol/L,2283
39131153,828992375,3353226,9424,7,Base Excess,-1.0,-1.0,mEq/L,mmol/L,9424
39131183,829356081,3353226,912,7,Base Excess,2.0,2.0,mEq/L,mmol/L,912
39131213,829720084,3353226,-135,7,Base Excess,3.0,3.0,mEq/L,mmol/L,-135
39131239,829263787,3353226,6559,7,Base Excess,-2.0,-2.0,mEq/L,mmol/L,6559
39131277,829315938,3353226,4029,7,Base Excess,-4.0,-4.0,mEq/L,mmol/L,4029
39131693,829488903,3353251,428,7,Base Excess,-9.0,-9.0,mEq/L,mmol/L,428
39131753,829836635,3353251,-144,7,Base Excess,-8.0,-8.0,mEq/L,mmol/L,-144
39131801,829411607,3353251,-50,7,Base Excess,-12.0,-12.0,mEq/L,mmol/L,-50
39131812,829883664,3353251,3864,7,Base Excess,5.0,5.0,mEq/L,mmol/L,3864
39131846,829261279,3353251,9901,7,Base Excess,4.0,4.0,mEq/L,mmol/L,9901
39131877,829493610,3353251,-169,7,Base Excess,-16.0,-16.0,mEq/L,mmol/L,-169
39131900,829814910,3353251,11054,7,Base Excess,8.0,8.0,mEq/L,mmol/L,11054
39131988,829768492,3353251,1065,7,Base Excess,1.0,1.0,mEq/L,mmol/L,1065
39132050,828968829,3353251,4510,7,Base Excess,6.0,6.0,mEq/L,mmol/L,4510
39132105,829612146,3353251,2448,7,Base Excess,3.0,3.0,mEq/L,mmol/L,2448
39132119,829742577,3353251,82,7,Base Excess,-16.0,-16.0,mEq/L,mmol/L,82
39132155,829361103,3353251,972,7,Base Excess,2.0,2.0,mEq/L,mmol/L,972
39132177,829803164,3353251,5598,7,Base Excess,6.0,6.0,mEq/L,mmol/L,5598
39132244,829194479,3353251,310,7,Base Excess,-12.0,-12.0,mEq/L,mmol/L,310
39132366,829249134,3353254,4237,7,Base Excess,-3.0,-3.0,mEq/L,mmol/L,4237

In [24]:
df_lab.loc[df_lab['labname'].str.contains('ast',case=False)]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
74,49485526,141168,2026,1,AST (SGOT),4257.0,4257,Units/L,Units/L,2100
93,47753722,141168,516,1,AST (SGOT),59.0,59,Units/L,Units/L,540
134,43871517,141168,1133,1,AST (SGOT),878.0,878,Units/L,Units/L,1240
166,48867927,141178,-280,1,AST (SGOT),40.0,40,Units/L,Units/L,-212
323,45504376,141194,312,1,AST (SGOT),24.0,24,Units/L,Units/L,348
408,48502703,141194,-923,1,AST (SGOT),15.0,15,Units/L,Units/L,-894
544,47655453,141196,628,1,AST (SGOT),15.0,15,Units/L,Units/L,739
557,42771194,141196,3600,1,AST (SGOT),14.0,14,Units/L,Units/L,3682
633,47926905,141197,-179,1,AST (SGOT),17.0,17,Units/L,Units/L,-141
703,46463455,141203,-473,1,AST (SGOT),26.0,26,Units/L,Units/L,-412
736,47256037,141203,-1580,1,AST (SGOT),37.0,37,Units/L,Units/L,-1500
757,46463436,141203,1091,1,AST (SGOT),22.0,22,Units/L,Units/L,1158
800,47993018,141208,-139,1,AST (SGOT),53.0,53,Units/L,Units/L,-112
1002,44067828,141229,-106,1,AST (SGOT),48.0,48,Units/L,Units/L,-77
1635,44047366,141244,6370,1,AST (SGOT),36.0,36,Units/L,Units/L,6474
1732,43033762,141244,-10880,1,AST (SGOT),26.0,26,Units/L,Units/L,-10824
2006,46096056,141260,-119,1,AST (SGOT),35.0,35,Units/L,Units/L,-71
2065,42971386,141264,-100,1,AST (SGOT),55.0,55,Units/L,Units/L,-71
2422,47634193,141266,-703,1,AST (SGOT),37.0,37,Units/L,Units/L,-667
2465,48588683,141266,6557,1,AST (SGOT),31.0,31,Units/L,Units/L,6588
2471,47893765,141266,5147,1,AST (SGOT),32.0,32,Units/L,Units/L,5184
2489,43192182,141266,833,1,AST (SGOT),76.0,76,Units/L,Units/L,874
2501,48939589,141266,3715,1,AST (SGOT),36.0,36,Units/L,Units/L,3746
2511,46438371,141266,2214,1,AST (SGOT),46.0,46,Units/L,Units/L,2245
2681,47369603,141284,180,1,AST (SGOT),24.0,24,Units/L,Units/L,222
2713,44114496,141284,2110,1,AST (SGOT),38.0,38,Units/L,Units/L,2156
2819,44734236,141288,-268,1,AST (SGOT),17.0,17,Units/L,Units/L,-231
2990,46021318,141296,-1827,1,AST (SGOT),128.0,128,Units/L,Units/L,-1507
3059,48494176,141296,5423,1,AST (SGOT),199.0,199,Units/L,Units/L,5488
3061,46834562,141296,-342,1,AST (SGOT),159.0,159,Units/L,Units/L,-294
...,...,...,...,...,...,...,...,...,...,...
39126160,824204501,3353145,256,1,AST (SGOT),24.0,24,Units/L,IU/L,288
39126193,823905276,3353145,3476,1,AST (SGOT),16.0,16,Units/L,IU/L,3510
39126221,823219788,3353147,-222,1,AST (SGOT),47.0,47,Units/L,IU/L,-179
39126263,823189204,3353147,122,1,AST (SGOT),41.0,41,Units/L,IU/L,146
39126264,822967939,3353147,676,1,AST (SGOT),33.0,33,Units/L,IU/L,710
39126316,823703105,3353147,901,1,AST (SGOT),31.0,31,Units/L,IU/L,945
39126438,824227297,3353184,575,1,AST (SGOT),30.0,30,Units/L,IU/L,608
39126489,824091057,3353190,0,1,AST (SGOT),19.0,19,Units/L,IU/L,34
39126830,822452741,3353194,-126,1,AST (SGOT),87.0,87,Units/L,IU/L,-34
39126840,822533927,3353194,1640,1,AST (SGOT),51.0,51,Units/L,IU/L,1686
39127047,822738166,3353196,4698,1,AST (SGOT),23.0,23,Units/L,IU/L,4735
39127363,823003323,3353197,-1790,1,AST (SGOT),19.0,19,Units/L,IU/L,-1752
39127429,822228455,3353197,15000,1,AST (SGOT),71.0,71,Units/L,IU/L,15036
39128745,822482326,3353198,10698,1,AST (SGOT),32.0,32,Units/L,IU/L,10739
39128858,822368388,3353198,58988,1,AST (SGOT),22.0,22,Units/L,IU/L,59048
39128946,823491804,3353198,32397,1,AST (SGOT),20.0,20,Units/L,IU/L,32442
39129355,824120064,3353198,4928,1,AST (SGOT),49.0,49,Units/L,IU/L,4963
39129389,822029134,3353198,61193,1,AST (SGOT),16.0,16,Units/L,IU/L,61259
39129450,822903101,3353198,694,1,AST (SGOT),33.0,33,Units/L,IU/L,732
39129864,822373903,3353200,29331,1,AST (SGOT),19.0,19,Units/L,IU/L,29378
39129912,822419789,3353200,29331,1,AST (SGOT),18.0,18,Units/L,IU/L,29375
39130644,822469966,3353201,5332,1,AST (SGOT),35.0,35,Units/L,IU/L,5372
39130845,823878147,3353213,3000,1,AST (SGOT),24.0,24,Units/L,IU/L,3026
39130875,822443582,3353213,-78,1,AST (SGOT),50.0,50,Units/L,IU/L,-47
39130899,823543801,3353216,35,1,AST (SGOT),20.0,20,Units/L,IU/L,117
39131132,822674527,3353226,726,1,AST (SGOT),31.0,31,Units/L,IU/L,764
39131354,822640945,3353237,167,1,AST (SGOT),18.0,18,Units/L,IU/L,209
39131719,823732515,3353251,8246,1,AST (SGOT),117.0,117,Units/L,IU/L,8283
39132022,822755452,3353251,-60,1,AST (SGOT),264.0,264,Units/L,IU/L,1
39132340,822427680,3353254,-256,1,AST (SGOT),15.0,15,Units/L,IU/L,-221

In [25]:
df_lab.loc[df_lab['labname'].str.contains('bun',case=False)]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
8,47753731,141168,516,1,BUN,26.0,26,mg/dL,mg/dL,540
13,49485535,141168,2026,1,BUN,29.0,29,mg/dL,mg/dL,2090
38,43871526,141168,1133,1,BUN,27.0,27,mg/dL,mg/dL,1240
155,48867936,141178,-280,1,BUN,11.0,11,mg/dL,mg/dL,-212
169,43947704,141179,750,1,BUN,21.0,21,mg/dL,mg/dL,772
183,45190714,141179,1487,1,BUN,14.0,14,mg/dL,mg/dL,1552
205,49190157,141179,82,1,BUN,20.0,20,mg/dL,mg/dL,106
229,45477454,141194,2876,1,BUN,31.0,31,mg/dL,mg/dL,2939
231,48003888,141194,8762,1,BUN,20.0,20,mg/dL,mg/dL,8834
240,46470590,141194,11658,1,BUN,13.0,13,mg/dL,mg/dL,11721
246,48299232,141194,762,1,BUN,30.0,30,mg/dL,mg/dL,797
248,49516056,141194,10397,1,BUN,15.0,15,mg/dL,mg/dL,10450
265,45504385,141194,312,1,BUN,31.0,31,mg/dL,mg/dL,348
284,44268058,141194,1630,1,BUN,29.0,29,mg/dL,mg/dL,1767
308,44597944,141194,1237,1,BUN,31.0,31,mg/dL,mg/dL,1276
344,45632962,141194,5897,1,BUN,26.0,26,mg/dL,mg/dL,5951
365,42849586,141194,4663,1,BUN,30.0,30,mg/dL,mg/dL,4723
398,48568782,141194,7303,1,BUN,24.0,24,mg/dL,mg/dL,7365
428,45037867,141194,2223,1,BUN,31.0,31,mg/dL,mg/dL,2295
468,44831855,141194,2998,1,BUN,31.0,31,mg/dL,mg/dL,3053
508,45058294,141194,-923,1,BUN,41.0,41,mg/dL,mg/dL,-894
559,42771190,141196,3600,1,BUN,24.0,24,mg/dL,mg/dL,3682
577,47655449,141196,628,1,BUN,16.0,16,mg/dL,mg/dL,739
629,47926914,141197,-179,1,BUN,14.0,14,mg/dL,mg/dL,-141
701,45761375,141203,1,1,BUN,9.0,9,mg/dL,mg/dL,78
715,46463464,141203,-473,1,BUN,9.0,9,mg/dL,mg/dL,-412
740,47256046,141203,-1580,1,BUN,10.0,10,mg/dL,mg/dL,-1499
768,46463445,141203,1091,1,BUN,11.0,11,mg/dL,mg/dL,1158
814,49115738,141208,-139,1,BUN,13.0,13,mg/dL,mg/dL,-112
820,46166011,141227,1362,1,BUN,32.0,32,mg/dL,mg/dL,1385
...,...,...,...,...,...,...,...,...,...,...
39131427,823330717,3353237,7743,1,BUN,16.0,16,mg/dL,mg/dL,7813
39131433,824272210,3353237,1959,1,BUN,29.0,29,mg/dL,mg/dL,2021
39131472,822043834,3353237,6255,1,BUN,17.0,17,mg/dL,mg/dL,6340
39131495,824192053,3353237,3342,1,BUN,29.0,29,mg/dL,mg/dL,3398
39131557,823138273,3353251,11058,1,BUN,83.0,83,mg/dL,mg/dL,11098
39131597,823004925,3353251,13970,1,BUN,91.0,91,mg/dL,mg/dL,14009
39131658,823309072,3353251,12458,1,BUN,89.0,89,mg/dL,mg/dL,12495
39131667,824196154,3353251,18327,1,BUN,55.0,55,mg/dL,mg/dL,18376
39131699,824031932,3353251,16867,1,BUN,66.0,66,mg/dL,mg/dL,16914
39131759,823732524,3353251,8246,1,BUN,46.0,46,mg/dL,mg/dL,8283
39131799,823534078,3353251,9644,1,BUN,73.0,73,mg/dL,mg/dL,9677
39131806,824128197,3353251,1490,1,BUN,31.0,31,mg/dL,mg/dL,1538
39131850,822185028,3353251,765,1,BUN,31.0,31,mg/dL,mg/dL,797
39131872,822970010,3353251,2541,1,BUN,36.0,36,mg/dL,mg/dL,2588
39132012,823178479,3353251,15598,1,BUN,77.0,77,mg/dL,mg/dL,15622
39132020,822811989,3353251,1127,1,BUN,30.0,30,mg/dL,mg/dL,1164
39132043,822463102,3353251,3863,1,BUN,38.0,38,mg/dL,mg/dL,3897
39132047,822273917,3353251,995,1,BUN,31.0,31,mg/dL,mg/dL,1031
39132176,823763662,3353251,5459,1,BUN,36.0,36,mg/dL,mg/dL,5510
39132178,822448504,3353251,-217,1,BUN,19.0,19,mg/dL,mg/dL,-151
39132228,823615010,3353251,6868,1,BUN,40.0,40,mg/dL,mg/dL,6908
39132245,822355179,3353251,409,1,BUN,30.0,30,mg/dL,mg/dL,451
39132259,822488872,3353251,1849,1,BUN,32.0,32,mg/dL,mg/dL,1894
39132271,823528304,3353254,2610,1,BUN,31.0,31,mg/dL,mg/dL,2664
39132301,822738546,3353254,1218,1,BUN,45.0,45,mg/dL,mg/dL,1247
39132326,822591625,3353254,1844,1,BUN,38.0,38,mg/dL,mg/dL,1876
39132335,823276083,3353254,5558,1,BUN,16.0,16,mg/dL,mg/dL,5626
39132416,823303097,3353254,-256,1,BUN,42.0,42,mg/dL,mg/dL,-221
39132422,824422436,3353254,4144,1,BUN,21.0,21,mg/dL,mg/dL,4196
39132471,823358354,3353263,-7,1,BUN,13.0,13,mg/dL,mg/dL,17

In [26]:
df_lab.loc[df_lab['labname'].str.contains('Alkalinephos',case=False)]

Empty DataFrame
Columns: [labid, patientunitstayid, labresultoffset, labtypeid, labname, labresult, labresulttext, labmeasurenamesystem, labmeasurenameinterface, labresultrevisedoffset]
Index: []

In [28]:
df_lab.loc[df_lab['labname'].str.contains('Calcium',case=False)]

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
55,43871522,141168,1133,1,calcium,9.2,9.2,mg/dL,mg/dL,1240
62,49485531,141168,2026,1,calcium,8.5,8.5,mg/dL,mg/dL,2090
75,47753727,141168,516,1,calcium,8.8,8.8,mg/dL,mg/dL,540
149,48867932,141178,-280,1,calcium,8.0,8.0,mg/dL,mg/dL,-212
180,45190716,141179,1487,1,calcium,7.9,7.9,mg/dL,mg/dL,1552
187,43947706,141179,750,1,calcium,7.8,7.8,mg/dL,mg/dL,772
207,49190159,141179,82,1,calcium,8.6,8.6,mg/dL,mg/dL,106
239,48003890,141194,8762,1,calcium,8.0,8.0,mg/dL,mg/dL,8834
245,45477451,141194,2876,1,calcium,7.0,7.0,mg/dL,mg/dL,2939
257,45504381,141194,312,1,calcium,8.5,8.5,mg/dL,mg/dL,348
264,49516058,141194,10397,1,calcium,8.2,8.2,mg/dL,mg/dL,10450
286,46470592,141194,11658,1,calcium,8.8,8.8,mg/dL,mg/dL,11721
290,44268055,141194,1630,1,calcium,7.4,7.4,mg/dL,mg/dL,1767
300,48299229,141194,762,1,calcium,7.4,7.4,mg/dL,mg/dL,797
311,42849583,141194,4663,1,calcium,7.6,7.6,mg/dL,mg/dL,4723
340,44597941,141194,1237,1,calcium,7.4,7.4,mg/dL,mg/dL,1276
360,45632964,141194,5897,1,calcium,7.8,7.8,mg/dL,mg/dL,5951
367,45037864,141194,2223,1,calcium,6.9,6.9,mg/dL,mg/dL,2295
444,48568784,141194,7303,1,calcium,8.0,8.0,mg/dL,mg/dL,7365
480,44831852,141194,2998,1,calcium,7.0,7.0,mg/dL,mg/dL,3053
514,45058291,141194,-923,1,calcium,9.9,9.9,mg/dL,mg/dL,-894
545,42771192,141196,3600,1,calcium,8.7,8.7,mg/dL,mg/dL,3682
592,47655451,141196,628,1,calcium,9.0,9.0,mg/dL,mg/dL,739
641,47926910,141197,-179,1,calcium,9.0,9.0,mg/dL,mg/dL,-141
673,46463441,141203,1091,1,calcium,8.0,8.0,mg/dL,mg/dL,1158
688,46463460,141203,-473,1,calcium,8.0,8.0,mg/dL,mg/dL,-412
694,45761372,141203,1,1,calcium,8.6,8.6,mg/dL,mg/dL,78
744,47256042,141203,-1580,1,calcium,8.5,8.5,mg/dL,mg/dL,-1499
806,49115735,141208,-139,1,calcium,9.1,9.1,mg/dL,mg/dL,-112
885,48437484,141227,-1566,1,calcium,8.4,8.4,mg/dL,mg/dL,-1518
...,...,...,...,...,...,...,...,...,...,...
39131663,823732520,3353251,8246,1,calcium,8.1,8.1,mg/dL,mg/dL,8283
39131695,823534075,3353251,9644,1,calcium,8.4,8.4,mg/dL,mg/dL,9677
39131703,823737620,3353251,3863,1,ionized calcium,3.8,3.8,mg/dL,mg/dL,3921
39131731,824031935,3353251,16867,1,calcium,9.1,9.1,mg/dL,mg/dL,16914
39131746,823309069,3353251,12458,1,calcium,9.0,9.0,mg/dL,mg/dL,12495
39131840,822811986,3353251,1127,1,calcium,8.0,8.0,mg/dL,mg/dL,1164
39131882,822185025,3353251,765,1,calcium,8.0,8.0,mg/dL,mg/dL,797
39131946,824128192,3353251,1490,1,calcium,7.9,7.9,mg/dL,mg/dL,1538
39131958,823934966,3353251,1490,1,ionized calcium,4.2,4.2,mg/dL,mg/dL,1554
39131999,822463097,3353251,3863,1,calcium,7.4,7.4,mg/dL,mg/dL,3897
39132028,823178476,3353251,15598,1,calcium,8.7,8.7,mg/dL,mg/dL,15622
39132031,822273914,3353251,995,1,calcium,8.1,8.1,mg/dL,mg/dL,1031
39132056,822036662,3353251,1127,1,ionized calcium,4.2,4.2,mg/dL,mg/dL,1171
39132064,822503252,3353251,6868,1,ionized calcium,4.4,4.4,mg/dL,mg/dL,6916
39132072,822311763,3353251,5459,1,ionized calcium,4.2,4.2,mg/dL,mg/dL,5524
39132099,822970007,3353251,2541,1,calcium,7.7,7.7,mg/dL,mg/dL,2588
39132186,822448501,3353251,-217,1,calcium,8.9,8.9,mg/dL,mg/dL,-151
39132204,823615007,3353251,6868,1,calcium,8.1,8.1,mg/dL,mg/dL,6908
39132226,823763657,3353251,5459,1,calcium,7.8,7.8,mg/dL,mg/dL,5510
39132239,822180892,3353251,409,1,ionized calcium,4.3,4.3,mg/dL,mg/dL,464
39132241,822488869,3353251,1849,1,calcium,7.8,7.8,mg/dL,mg/dL,1894
39132249,822355176,3353251,409,1,calcium,8.0,8.0,mg/dL,mg/dL,451
39132279,823528307,3353254,2610,1,calcium,6.8,6.8,mg/dL,mg/dL,2664
39132280,823335412,3353254,1501,1,ionized calcium,4.5,4.5,mg/dL,mg/dL,1529
39132289,822738549,3353254,1218,1,calcium,6.4,6.4,mg/dL,mg/dL,1247
39132317,822695456,3353254,4144,1,calcium,7.6,7.6,mg/dL,mg/dL,4196
39132334,822591628,3353254,1844,1,calcium,6.9,6.9,mg/dL,mg/dL,1876
39132349,823276086,3353254,5558,1,calcium,8.2,8.2,mg/dL,mg/dL,5626
39132410,823303094,3353254,-256,1,calcium,8.9,8.9,mg/dL,mg/dL,-221
39132439,823358351,3353263,-7,1,calcium,9.5,9.5,mg/dL,mg/dL,17